(() => {
  "use strict";
  const state = { user: null, designs: [], draft: null };
  const $ = (selector) => document.querySelector(selector);
  const escapeHtml = (value) => String(value ?? "").replace(/[&<>'"]/g, (character) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "'":"&#39;", '"':"&quot;" })[character]);
  const formatDate = (value) => new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date(value));
  const api = async (path, options={}) => { const response=await fetch(path,{credentials:"same-origin",...options,headers:options.body?{"Content-Type":"application/json"}:undefined}); const result=await response.json(); if(!response.ok) throw Object.assign(new Error(result.message),{status:response.status}); return result; };
  const icons = {
    designs:'<svg viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="16" rx="3"/><path d="M7 8h10v8H7z"/></svg>',
    material:'<svg viewBox="0 0 24 24"><path d="m12 3-8 4.5 8 4.5 8-4.5L12 3Z"/><path d="m4 12 8 4.5 8-4.5"/></svg>',
    recent:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>',
  };
  const designCard=(design)=>{const config=design.configuration||{};const summary=[config.Panel,config.Material,config.Module?`${config.Module} Module`:""].filter(Boolean).join(" · ");return `<article class="workspace-design"><div class="workspace-design-preview"><span class="workspace-design-reference">${escapeHtml(design.reference)}</span>${design.preview?`<img src="${design.preview}" alt="Preview of ${escapeHtml(design.name)}"/>`:"<span>Preview unavailable</span>"}</div><div class="workspace-design-body"><div class="workspace-design-meta"><time>${escapeHtml(formatDate(design.createdAt))}</time><span class="workspace-design-status">${escapeHtml(design.status)}</span></div><h3>${escapeHtml(design.name)}</h3><p class="workspace-design-summary">${escapeHtml(summary||"Panel configuration")}</p><details><summary>View configuration</summary><dl>${Object.entries(config).map(([key,value])=>`<div><dt>${escapeHtml(key)}</dt><dd title="${escapeHtml(value)}">${escapeHtml(value)}</dd></div>`).join("")}</dl></details><div class="workspace-design-actions"><a class="workspace-design-pdf" href="/api/designs/${encodeURIComponent(design.id)}/pdf" download>Download order PDF</a><button class="workspace-design-action" type="button" data-edit-design="${design.id}">Edit</button><button class="workspace-design-action" type="button" data-duplicate-design="${design.id}">Duplicate</button><button class="workspace-design-delete" type="button" data-delete-design="${design.id}">Delete</button></div></div></article>`};
  const renderDesigns=()=>{const query=$("#workspaceSearch").value.trim().toLowerCase();const items=state.designs.filter((design)=>`${design.name} ${design.reference} ${Object.values(design.configuration||{}).join(" ")}`.toLowerCase().includes(query));$("#workspaceDesigns").innerHTML=items.length?items.map(designCard).join(""):'<div class="workspace-empty"><strong>No matching designs</strong><span>Try another search or create a new panel.</span><a href="/">Open configurator</a></div>';};
  const render=()=>{const materials=new Set(state.designs.map((design)=>design.configuration?.Material).filter(Boolean));const draft=$("#workspaceDraft");$("#workspaceGreeting").textContent=`Welcome, ${state.user.name.split(/\s+/)[0]}`;$("#workspaceDesignCount").textContent=`${state.designs.length} ${state.designs.length===1?"saved panel":"saved panels"}`;if(state.draft){const config=state.draft.configuration||{};draft.innerHTML=`<span>Unfinished design</span><strong>${escapeHtml(config.Panel||"Panel")} · ${escapeHtml(config.Material||"Material")} · ${escapeHtml(config.Module||"?")} Module</strong><em>Resume where you left off →</em>`;draft.hidden=false;}else{draft.hidden=true;}$("#workspaceStats").innerHTML=`<div class="workspace-stat"><span class="workspace-stat-icon">${icons.designs}</span><div><span>Saved designs</span><strong>${state.designs.length}</strong></div></div><div class="workspace-stat"><span class="workspace-stat-icon">${icons.material}</span><div><span>Materials explored</span><strong>${materials.size}</strong></div></div><div class="workspace-stat"><span class="workspace-stat-icon">${icons.recent}</span><div><span>Latest activity</span><strong>${state.designs[0]?formatDate(state.designs[0].createdAt):"—"}</strong></div></div>`;renderDesigns();};
  const showLogin=(message="")=>{$("#workspaceLogin").hidden=false;$("#workspaceDashboard").hidden=true;$("#workspaceLogout").hidden=true;if(message){$("#workspaceLoginMessage").textContent=message;$("#workspaceLoginMessage").hidden=false;}};
  const load=async()=>{try{const me=await api("/api/auth/me");if(!me.user){showLogin();return;}state.user=me.user;const [designResult,draftResult]=await Promise.all([api("/api/designs"),api("/api/draft")]);state.designs=designResult.designs;state.draft=draftResult.draft;$("#workspaceLogin").hidden=true;$("#workspaceDashboard").hidden=false;$("#workspaceLogout").hidden=false;render();}catch(error){showLogin(error.message);}};
  $("#workspaceLoginForm").addEventListener("submit",async(event)=>{event.preventDefault();const button=event.target.querySelector("button");button.disabled=true;$("#workspaceLoginMessage").hidden=true;try{await api("/api/auth/login",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(event.target)))});await load();}catch(error){showLogin(error.message);}finally{button.disabled=false;}});
  $("#workspaceLogout").addEventListener("click",async()=>{await api("/api/auth/logout",{method:"POST",body:"{}"});state.user=null;state.designs=[];state.draft=null;showLogin("You have been signed out.");});
  $("#workspaceSearch").addEventListener("input",renderDesigns);
  $("#workspaceDesigns").addEventListener("click",async(event)=>{const edit=event.target.closest("[data-edit-design]");const duplicate=event.target.closest("[data-duplicate-design]");const remove=event.target.closest("[data-delete-design]");if(edit){const result=await api(`/api/designs/${edit.dataset.editDesign}`);sessionStorage.setItem("autronx-edit-design",JSON.stringify({userId:state.user.id,design:result.design}));window.location.assign("/");return;}if(duplicate){const result=await api(`/api/designs/${duplicate.dataset.duplicateDesign}/duplicate`,{method:"POST",body:"{}"});state.designs.unshift(result.design);render();return;}if(!remove||!confirm("Delete this saved design?"))return;await api(`/api/designs/${remove.dataset.deleteDesign}`,{method:"DELETE",body:"{}"});state.designs=state.designs.filter((design)=>design.id!==remove.dataset.deleteDesign);render();});
  load();
})();
